package com.econtabil.integration.domain.enumerate;

public class Enum {
	public enum PersistenceActionEnum {
		INSERT, UPDATE, DELETE, FETCH, NONE
	}

	public enum DocumentoTypeEnum {
		/** The centralized. */
		CNPJ,

		/** The not centralized. */
		CPF,

		/** The mixed. */
		IM,

		RG,

		TITULOELEITOR,

		RESERVISTA,

		CERTIDAONEGATIVA,

		IES, IIE,

		IE,

		IF,

		INSCRESTSUBSTTRIB,

		/** The unknown. */
		CERTIDADONASCIMENTO,

		INDICADORIE,

		IDESTRANGEIRO,

		NUNINSJUNTCOMERCIAL,

		CRC,

		CRM,

		OAB
	}

	public enum EmailTypeEnum {
		PARTICULAR, VENDAS, COMPRAS, NFE, SAC, REPRESENTANTE, DIRETOR, GERENTE, PRINCIPAL
	}

	public enum EnderecoTypeEnum {
		RESIDENCIAL, ENTREGA, COBRANCA, PRINCIPAL
	}

	public enum AcaoEnum {
		INSERT, UPDATE, DELETE, FETCHALL, FETCHID
	}

	public enum CdStatusTypeEnum {
		ATIVO, INATIVO, DELETADO, SUSPENSO, NEGATIVADO, ANALISANDO
	}

	public enum PermissaoTypeEnum {
		SYSTEM, CONTADOR, PARCEIRO, MATRIX, NORMAL
	}

	public enum TrueValueTypeEnum {
		SYSTEM, CONTADOR, PARCEIRO, MATRIX, NORMAL
	}

	public enum TypeEnum {
		SYSTEM, CONTADOR, PARCEIRO, MATRIX, NORMAL
	}

	public enum TelefoneTypeEnum {
		PARTICULAR, VENDAS, COMPRAS, NFE, SAC, REPRESENTANTE, DIRETOR, GERENTE, EMPRESA, CELULAR
	}

	public enum TabelaEnum {

		REGIME, EMPRESA, DOCUMENTO, EMAIL, ENDERECO, TELEFONE, SOCIO, HISTORICO, CNAE, CSOSN,

		NCM, CIDADE, CNAEPORRELACIONAMENTO, ESTADO, UNIMED,

		/** The low. */
		CFOP, FUNCIONARIO, CLIENTE, FORNECEDOR, TRANSPORTADOR, CONDPAG,

		CONVENIO, SALARIO, PESSOA, PROFISSAO, CONVENIOPESSOA, CONDPAGPESSOA, TIPOPAG, TIPOPAGREG, BANCO, AGENCIA,

		BANCOPESOA, CONTATO, CONTATOITENS, ORDEMSERVICO, ORDEMSERVICOITENS, ORDEMSERVICOTYPES, ORDEMSERVICOSTATUS, TABELA,

		ATRIBUTOS, EVENTOS, BENEFICIOS, CUSTO, NOTE, HORAFUNC, PRODUTO, NOTAFISCAL, ORCAMENTO, PEDIDOCOMPRAS, CONTAS, MARCA, DEPOSITO, FILIAL, SERVICO, PLANO, MEDICO, PACIENTE, EXAME, PLANOSAUDE, CONSULTA, USUARIO, CONDOMINIO, ADVOCACIA, CLINICA, SITE, CONTASPAGAR, CONTASRECEBER, BAIXARTITULO, TIPOBAIXA, TITULO, FORMAPG, CONTACORRENTE, CAIXA, PRODUTOPARENT, ADVOGADO, MARCAPRODUTO, GRUPO, SUBGRUPO, CUSTOITENS, ESTOQUE, PORCAO, PORCAOITENS, RENTABILIDADE, RENTABILIDADEITENS, TRIBUTACAO, BOLETO, GRUPOTRABALHO, CONFIGALERTAS,

		CONFIGCARNE,

		CONFIGENTRADA,

		CONFIGFISCAL,

		CONFIGGERAL,

		CONFIGPRODUTO,

		CONFIGSMTP,

		CONFIGURACAO,

		CONFIGURACAONFE,

		DOISVALOR,

		SINDICO,

		INQUILINO,

		AUDIENCIA,

		PROCESSO,

		BAIXATITULO,

		COTACAO,

		AVISO,

		CLASSES,

		INTERFACE,

		FIELD,

		PLANOBYEMPRESA,

		CONFIGVENDAS,

		ICMS,

		PIS,

		IPI,

		COFINS,

		CATEGORIA,

		PRODUTOEMPRESA,

		ROLE,

		PAGINA,

		VALIDACAO,

		AJUDA,

		MENU,

		USERROLES,

		CONHECIMENTOTRANSPORTE,

		NOTAFISCALITENS,

		NFNOTA,

		NFNOTAINFO,

		NFNOTAINFOIDENTIFICACAO,

		NFINFOMODELO1POR1AREFERENCIADA,

		NFINFOREFERENCIADA,

		NFINFOPRODUTORRURALREFERENCIADA,

		NFNOTAINFOEMITENTE,

		NFNOTAINFOAVULSA, NFNOTAINFODESTINATARIO,

		NFNOTAINFOLOCAL, NFPESSOAAUTORIZADADOWNLOADNFE, NFNOTAINFOTOTAL, NFNOTAINFOICMSTOTAL, NFNOTAINFOISSQNTOTAL, NFNOTAINFORETENCOESTRIBUTOS, NFNOTAINFOTRANSPORTE, NFNOTAINFORETENCAOICMSTRANSPORTE, NFNOTAINFOTRANSPORTADOR, NFNOTAINFOVEICULO, NFNOTAINFOREBOQUE, NFNOTAINFOCOBRANCA, NFNOTAINFODUPLICATA, NFNOTAINFOFATURA, NFNOTAINFOCARTAO, NFNOTAINFOPAGAMENTO, NFNOTAINFOINFORMACOESADICIONAIS, NFNOTAINFOOBSERVACAO, NFNOTAINFOPROCESSOREFERENCIADO, NFNOTAINFOEXPORTACAO, NFNOTAINFOCOMPRA, NFNOTAINFOCANAFORNECIMENTODIARIO, NFNOTAINFOCANA, NFNOTAINFOCANADEDUCAO, NFNOTAINFOSUPLEMENTAR, NFINFOCUPOMFISCALREFERENCIADO,

		NOTAFISCALSAIDA, ICMSOPINTER, NFNOTAINFOITEM, NFNOTAINFOITEMPRODUTO, NFNOTAINFOITEMPRODUTODECLARACAOIMPORTACAO, NFNOTAINFOITEMPRODUTODECLARACAOIMPORTACAOADICAO, NFNOTAINFOITEMDETALHEEXPORTACAO, NFNOTAINFOITEMEXPORTACAOINDIRETA, NFNOTAINFOITEMPRODUTOVEICULO, NFNOTAINFOITEMPRODUTOMEDICAMENTO, NFNOTAINFOITEMPRODUTOARMAMENTO, NFNOTAINFOITEMPRODUTOCOMBUSTIVELCIDE, NFINFORMACAOIMPOSTODEVOLVIDO, NFNOTAINFOITEMIMPOSTO, NFNOTAINFOITEMIMPOSTOICMS, NFNOTAINFOITEMIMPOSTOICMS00, NFNOTAINFOITEMIMPOSTOICMS10, NFNOTAINFOITEMIMPOSTOICMS20, NFNOTAINFOITEMIMPOSTOICMS30, NFNOTAINFOITEMIMPOSTOICMS40, NFNOTAINFOITEMIMPOSTOICMS51, NFNOTAINFOITEMIMPOSTOICMS60, NFNOTAINFOITEMIMPOSTOICMS70, NFNOTAINFOITEMIMPOSTOICMS90, NFNOTAINFOITEMIMPOSTOICMSPARTILHADO, NFNOTAINFOITEMIMPOSTOICMSST, NFNOTAINFOITEMIMPOSTOICMSSN101, NFNOTAINFOITEMIMPOSTOICMSSN102, NFNOTAINFOITEMIMPOSTOICMSSN201, NFNOTAINFOITEMIMPOSTOICMSSN202, NFNOTAINFOITEMIMPOSTOICMSSN500, NFNOTAINFOITEMIMPOSTOICMSSN900, NFNOTAINFOITEMIMPOSTOIPI, NFNOTAINFOITEMIMPOSTOIPITRIBUTADO, NFNOTAINFOITEMIMPOSTOIPINAOTRIBUTADO, NFNOTAINFOITEMIMPOSTOIMPORTACAO, NFNOTAINFOITEMIMPOSTOISSQN, NFNOTAINFOITEMIMPOSTOPIS, NFNOTAINFOITEMIMPOSTOPISALIQUOTA, NFNOTAINFOITEMIMPOSTOPISQUANTIDADE, NFNOTAINFOITEMIMPOSTOPISNAOTRIBUTADO, NFNOTAINFOITEMIMPOSTOPISOUTRASOPERACOES, NFNOTAINFOITEMIMPOSTOPISST, NFNOTAINFOITEMIMPOSTOCOFINS, NFNOTAINFOITEMIMPOSTOCOFINSALIQUOTA, NFNOTAINFOITEMIMPOSTOCOFINSQUANTIDADE, NFNOTAINFOITEMIMPOSTOCOFINSNAOTRIBUTAVEL, NFNOTAINFOITEMIMPOSTOCOFINSOUTRASOPERACOES, NFNOTAINFOITEMIMPOSTOCOFINSST, NFNOTAINFOITEMIMPOSTOICMSUFDESTINO, NFIMPOSTODEVOLVIDO, NFNOTAINFOITEMPRODUTOCOMBUSTIVEL, PROCESSOSTATUS, DIASHORAS, ESPECIALIDADE, COMPROMISSO, ADVOGADOS, ENVOLVIDOS, PARTICIPANTE, PARTICIPANTEEXTERNO, CLIENTECOMPROMISSO, ARQUIVO, PROCESSOUSUARIOS, PROCESSOCLIENTE, CONTA, DIASSEMANA
	}

	public enum ProcessoTypeEnum {
		INICIAL, PARALISADO, ANDAMENTO, INTERROMPIDO, FINALIZADO, AGUARDANDODOCUMENTOS
	}
	
	//CfopTypeEnum
	public enum CfopTypeEnum {
		ENTRADA,SAIDA,SERVICO,EXPORTACAO
	}
	
	public enum ContasTypeEnum {
		PAGAR,RECEBER,OUTROS
	}
	public enum ContatoStatusEnum {
		ABERTO,FECHADO,PENDENDE,AGUARDANDO_SYS,AGUARDANDO_CON
	}
	
	public enum ContatoTypeEnum {
		COBRANCA,VENDAS,INFORMATIVO,PROMOCOES,SISTEMA,PARCERIAS,OUTROS
	}
	
	public enum EmpresaTypeEnum {
		SYSTEM,PARCEIRO,CONTABILIDADE,NORMAL,MATRIZ,FILIAL,ADVOCACIA,CLINICA,CONDOMINIO
	}
	
	public enum NotificationTypeEnum {
		SYSTEM,PARCEIRO,CONTABILIDADE,NORMAL,MATRIZ,FILIAL
	}
	
	public enum NotaTypeEnum {
		ENTRADA,SAIDA,TRANSPORTE,SERVICO,ORCAMENTO,PEDIDOVENDAS,PEDIDOCOMPRAS
	}
	
	public enum OrdemServicoTypeEnum {
		INICIAL,MINIMO,MAXIMO,ATUAL
	}
	
	public enum PessoaTypeEnum {

		CLIENTE,FORNECEDOR,FUNCIONARIO,TRANSPORTADOR,CONTADOR,SOCIO,MEDICO,PACIENTE,ADVOGADO,INQUILINO,SINDICO,CONSFINAL

	}
	
	public enum EstoqueTypeEnum {
		INICIAL,MINIMO,MAXIMO,ATUA

	}
	
	public enum PrecoTypeEnum {
		CUSTO,COMPRA,VENDA,PROMOCAO,PLANO
	}
	
	public enum RentabilidadeTypeEnum {
		PERDA,PRODUTO
	}
	
	public enum SiteTypeEnum {
		PERDA,PRODUTO
	}
	
	public enum ServicoPlanoEnum {
		PLANO,SERVICO
	}
}
